[package]
name = "rl2-modloader-db"
version = "2.0.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
libsql = "0.9.1"
serde = "1.0.219"
shuttle-axum = "0.53.0"
shuttle-runtime = "0.53.0"
shuttle-secrets = "0.42.0"
tokio = "1.28.2"
tower-http = {version = "0.6.2", features = ["cors"]}
